---
title: "Proteomics"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: united
    highlight: textmate
editor_options:
  chunk_output_type: console
---

# Load packages
```{r message=FALSE, warning=FALSE}
library(viper)
library(aracne.networks)
library(dplyr)
library(plyr)
library(stringr)
library(Biobase)
library(EnsDb.Hsapiens.v86)
library(foreach)
library(doParallel)
dir.create("output/prot/",showWarnings = F)
```

# Define functions
```{r}
contains_special_characters <- function(strings) {
    # Define a regular expression pattern to match special characters
    pattern <- "[^A-Za-z0-9 ]"

    # Check if any string in the input vector contains special
    # characters
    contains_special <- grepl(pattern, strings)

    return(contains_special)
}
```

# Extract and process proteomics data

```{r}
df <- read.csv("data/omics_regulon_pairs.csv")
```

## Preprocess
```{r}
for (i in 1:nrow(df)) {
    exprsFile <- df$prot[i]
    exprs <- as.matrix(read.table(exprsFile, header = TRUE, sep = "\t",
        row.names = 1, as.is = TRUE))
    rownames(exprs) <- sub("\\..*$", "", rownames(exprs))
    exprs <- exprs[!duplicated(rownames(exprs)),]
    geneID <- ensembldb::select(EnsDb.Hsapiens.v86, keys = rownames(exprs),
        keytype = "GENEID", columns = c("SYMBOL", "ENTREZID", "GENEID"))
    rownames(exprs) <- plyr::mapvalues(rownames(exprs), from = geneID$GENEID,
        to = geneID$SYMBOL, warn_missing = FALSE)
    exprs <- exprs[!sapply(rownames(exprs), function(x) startsWith(x, "ENSG")),
        ]
    # Identify duplicated row names
    duplicated_rows <- duplicated(rownames(exprs))
    # Remove rows with duplicated row names
    cleaned_exprs <- exprs[!duplicated_rows,]
    cleaned_exprs <- cleaned_exprs[!contains_special_characters(rownames(cleaned_exprs)),]
    saveRDS(cleaned_exprs, paste("output/prot/count_matrix_", df$Lable[i], ".RDS", sep = ""))
}
```
