---
title: "Copy Number Variation"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: united
    highlight: textmate
editor_options:
  chunk_output_type: console
---

# Load packages
```{r message=FALSE, warning=FALSE}
library(viper)
library(aracne.networks)
library(dplyr)
library(plyr)
library(stringr)
library(Biobase)
library(EnsDb.Hsapiens.v86)
library(foreach)
library(doParallel)
dir.create("output/cnv/",showWarnings = F)
```

# Define functions
```{r}
contains_special_characters <- function(strings) {
    # Define a regular expression pattern to match special characters
    pattern <- "[^A-Za-z0-9 ]"
    # Check if any string in the input vector contains special
    # characters
    contains_special <- grepl(pattern, strings)
    return(contains_special)
}
```


# Extract and process CNV data
```{r}
df <- read.csv("data/omics_regulon_pairs.csv")
knitr::kable(df[,c('Lable','description')])
```

-2: homozygous deletion (2-copy loss). 
-1: heterozygous deletion (1-copy loss). 
0: normal diploid state. 
1: 1-copy gain. 
2: amplification (>= 2-copy gain). 

```{r}
Lable <- unique(substr(df$Lable, 1, 4))
CNV <- unique(df$CNV)
for (i in 1:length(CNV)) {
    exprs <- as.matrix(read.table(CNV[i], header = TRUE, sep = "\t",
        row.names = 1, as.is = TRUE))
    rownames(exprs) <- sub("\\..*$", "", rownames(exprs))
    geneID <- ensembldb::select(EnsDb.Hsapiens.v86, keys = rownames(exprs),
        keytype = "GENEID", columns = c("SYMBOL", "ENTREZID", "GENEID"))
    rownames(exprs) <- plyr::mapvalues(rownames(exprs), from = geneID$GENEID,
        to = geneID$SYMBOL, warn_missing = FALSE)
    exprs <- exprs[!sapply(rownames(exprs), function(x) startsWith(x, "ENSG")),
        ]
    # Identify duplicated row names
    duplicated_rows <- duplicated(rownames(exprs))
    # Remove rows with duplicated row names
    cleaned_exprs <- exprs[!duplicated_rows,]
    cleaned_exprs <- cleaned_exprs[!contains_special_characters(rownames(cleaned_exprs)),]
    saveRDS(cleaned_exprs, paste("output/cnv/count_matrix_", Lable[i], "_tumor.RDS", sep = ""))
    cleaned_exprs[] <- 0
    saveRDS(cleaned_exprs, paste("output/cnv/count_matrix_", Lable[i], "_normal.RDS", sep = ""))
}
```
