---
title: "Identify Kinase Regulators"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: united
    highlight: textmate
editor_options:
  chunk_output_type: console
---

# Load packages
```{r message=FALSE, warning=FALSE}
library(viper)
library(EnsDb.Hsapiens.v86)
library(foreach)
library(doParallel)
cluster <- makeCluster(5)
registerDoParallel(cluster)
dir.create("output/regulon/",showWarnings = FALSE)
set.seed(0)
```

## Process network and save as adj files
```{r}
df <- read.csv("data/KSA_gold_standard.csv")
geneID <- ensembldb::select(EnsDb.Hsapiens.v86, keys = df$UniProt.ID.1,
        keytype = "UNIPROTID", columns = c("SYMBOL", "ENTREZID", "GENEID","UNIPROTID"))
df$UniProt.ID.2 <- plyr::mapvalues(df$UniProt.ID.1, from = geneID$UNIPROTID,
        to = geneID$SYMBOL, warn_missing = FALSE)
df$ID <- paste(df$UniProt.ID.2,"_","S",df$Position,"_",df$seq_15, "\t", "1", sep="")
# Group by Regulator and concatenate elements of each group into strings
result <- aggregate(ID ~ Gene.name, data = df, FUN = function(x) paste(x, collapse = "\t"))
# Print the result
file <- file(paste("output/regulon/KSA_gold_standard.adj",
    sep = ""))
writeLines(paste(result$Gene.name,result$ID,sep = "\t"),file)
close(file)
```

# Generating the regulon object for pho
```{r eval=FALSE, include=TRUE}
set.seed(0)
for (name in c("kirc", "hnsc", "lusc", "luad", "paad")) {
    adjfile <- "output/regulon/KSA_gold_standard.adj"
    pho_normal <- readRDS(paste("output/pho/count_matrix_", name, "_normal.RDS",
        sep = ""))
    prot_normal <- readRDS(paste("output/prot/count_matrix_", name, "_normal.RDS",
        sep = ""))
    
    pho_tumor <- readRDS(paste("output/pho/count_matrix_", name, "_tumor.RDS",
        sep = ""))
    prot_tumor <- readRDS(paste("output/prot/count_matrix_", name, "_tumor.RDS",
        sep = ""))
    
    pho <- merge(pho_normal, pho_tumor, by = "row.names", all = FALSE)
    prot <- merge(prot_normal, prot_tumor, by = "row.names", all = FALSE)
    
    rownames(pho) <- pho$Row.names
    pho$Row.names <- NULL
    
    rownames(prot) <- prot$Row.names
    prot$Row.names <- NULL
    
    expr <- rbind(prot,pho)

    signature <- c(rep("normal", dim(pho_normal)[2]), rep("tumor", dim(pho_tumor)[2]))
    dset <- ExpressionSet(assayData = as.matrix(expr))
    dset$description <- factor(signature)
    regul <- aracne2regulon(adjfile, dset, verbose = TRUE)
    saveRDS(dset, paste("output/pho/dset_", name, ".RDS", sep = ""))
    saveRDS(regul, paste("output/pho/regul_", name, ".RDS", sep = ""))
}
```

# Run Viper on Phosphoproteome Data
```{r}
foreach(name = c("kirc", "hnsc", "lusc", "luad", "paad")) %dopar% {
    library(viper)
    dset <- readRDS(paste("output/pho/dset_", name, ".RDS",
        sep = ""))
    regulon <- readRDS(paste("output/pho/regul_", name, ".RDS", sep = ""))
    signature <- rowTtest(dset, "description", "tumor", "normal")
    signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * sign(signature$statistic))[,
        1]

    # NULL model by sample permutations
    nullmodel <- ttestNull(dset, "description", "tumor", "normal", per = 1000,
        repos = TRUE, verbose = FALSE)
    ## Normalized Enrichment Score (NES)
    mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE)
    temp <- summary(mrs, length(mrs$regulon))
    temp$Sign <- ifelse(temp$NES > 0, "+", "-")
    temp <- temp[temp$FDR < 0.1, ]
    temp <- temp[, c("Regulon", "NES", "Sign")]
    temp$NES <- abs(temp$NES)
    dir.create(paste("output/pho/",
        name, "/", sep = ""),showWarnings = F)
    write.table(temp, paste("output/pho/",
        name, "/kinase_regulators.txt", sep = ""), quote = F, sep = "\t", row.names = F,
        col.names = F)
}
```

