---
title: "Kinase Set Enrichment Analysis"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: united
    highlight: textmate
editor_options:
  chunk_output_type: console
---
```{r}
library(clusterProfiler)
library(ggplot2)
library(EnsDb.Hsapiens.v86)
full_name <- c("Human Kidney Renal Clear Cell Carcinoma",
"Human Head and Neck Squamous Carcinoma",
"Human Lung Squamous Carcinoma",
"Human Lung Adenocarcinoma",
"Human Pancreas Carcinoma")
names <- c("kirc", "hnsc", "lusc", "luad", "paad")
```

```{r fig.height=10, fig.width=10, message=FALSE, warning=FALSE, results="asis"}
ksa <- read.gmt("data/gold_standard_CoPheeKSA.gmt")
#meta <- read.csv("data/KSA_gold_standard.csv")
#meta <- meta[!duplicated(meta$seq_15),]
#geneID <- ensembldb::select(EnsDb.Hsapiens.v86, keys = meta$UniProt.ID.1, keytype = "UNIPROTID",
#        columns = c("SYMBOL", "UNIPROTID", "GENEID"))
#meta$UniProt.ID.1_SYMBOL <- plyr::mapvalues(meta$UniProt.ID.1, from = geneID$UNIPROTID,
#        to = geneID$SYMBOL, warn_missing = FALSE)
#meta$GS <- paste(meta$UniProt.ID.1_SYMBOL, meta$Position, sep="_")
#ksa$gene <- plyr::mapvalues(ksa$gene, from = meta$seq_15, to = meta$GS)

i <- 1
for (name in names) {
    cat("\n\n")
    cat("# ", full_name[i], sep = "")
    cat("\n\n")
    i <- i + 1
    dps <- read.csv(paste("output/DPS/", name, "_fc_0.05_kinases.csv",
        sep = ""))
    dps_plus <- dps[dps$Fold_Change > 0, ]
    dps_neg <- dps[dps$Fold_Change < 0, ]
    
    cat("\n\n")
    cat("## Positive")
    cat("\n\n")

    dps <- dps_plus
    dps <- dps[order(dps$Adjusted_P_Value, decreasing = TRUE), ]
    gse <- enricher(gene = dps$Seq, TERM2GENE = ksa)
    dir.create(paste("output/pho/", name, "/", sep = ""), showWarnings = FALSE)
    write.table(gse@result, paste("output/pho/", name, "/KSEA.csv",
        sep = ""))
    cat("\n\n")
    cat("### Barplots")
    cat("\n\n")
    print(mutate(gse, qscore = -log(p.adjust, base = 10)) %>%
        barplot(x = "qscore") + ggtitle(full_name[i]))

    cat("\n\n")
    cat("### Dotplots")
    cat("\n\n")
    print(dotplot(gse, showCategory = 30) + ggtitle(full_name[i]))

    cat("\n\n")
    cat("### Kinase-Concept Network")
    cat("\n\n")
    print(cnetplot(gse, color.params = list(foldChange = dps$Fold_Change)) +
        ggtitle(full_name[i]))

    cat("\n\n")
    cat("### Enrichment Map")
    cat("\n\n")
    print(emapplot(enrichplot::pairwise_termsim(gse)) + ggtitle(full_name[i]))
    
    cat("\n\n")
    cat("## Negative")
    cat("\n\n")

    dps <- dps_neg
    dps <- dps[order(dps$Adjusted_P_Value, decreasing = TRUE), ]
    gse <- enricher(gene = dps$Seq, TERM2GENE = ksa)
    dir.create(paste("output/pho/", name, "/", sep = ""), showWarnings = FALSE)
    write.table(gse@result, paste("output/pho/", name, "/KSEA.csv",
        sep = ""))
    cat("\n\n")
    cat("### Barplots")
    cat("\n\n")
    print(mutate(gse, qscore = -log(p.adjust, base = 10)) %>%
        barplot(x = "qscore") + ggtitle(full_name[i]))

    cat("\n\n")
    cat("### Dotplots")
    cat("\n\n")
    print(dotplot(gse, showCategory = 30) + ggtitle(full_name[i]))

    cat("\n\n")
    cat("### Kinase-Concept Network")
    cat("\n\n")
    print(cnetplot(gse, color.params = list(foldChange = dps$Fold_Change)) +
        ggtitle(full_name[i]))

    cat("\n\n")
    cat("### Enrichment Map")
    cat("\n\n")
    print(emapplot(enrichplot::pairwise_termsim(gse)) + ggtitle(full_name[i]))
}
```

