---
title: "TieDIE: Tied Diffusion for Subnetwork Discovery"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: textmate
editor_options:
  chunk_output_type: console
---

# TieDIE Results
```{r}
library(igraph)
knitr::opts_chunk$set(fig.width=20, fig.height=20) 
```

# KIRC
```{r}
sif_data <- read.table("output/TieDIE/input/kirc/TieDIE/tiedie.cn.sif", header = FALSE, stringsAsFactors = FALSE)
sif_graph <- graph_from_data_frame(sif_data[,c("V1","V3")], directed = FALSE)
plot(sif_graph, layout = layout.fruchterman.reingold, vertex.size = 5,vertex.frame.color= "white")
```

# LUSC
```{r}
sif_data <- read.table("output/TieDIE/input/lusc/TieDIE/tiedie.cn.sif", header = FALSE, stringsAsFactors = FALSE)
sif_graph <- graph_from_data_frame(sif_data[,c("V1","V3")], directed = FALSE)
plot(sif_graph, layout = layout.fruchterman.reingold, vertex.size = 5,vertex.frame.color= "white")
```

# LUAD
```{r}
sif_data <- read.table("output/TieDIE/input/luad/TieDIE/tiedie.cn.sif", header = FALSE, stringsAsFactors = FALSE)
sif_graph <- graph_from_data_frame(sif_data[,c("V1","V3")], directed = FALSE)
plot(sif_graph, layout = layout.fruchterman.reingold, vertex.size = 5,vertex.frame.color= "white")
```

# PAAD
```{r}
sif_data <- read.table("output/TieDIE/input/paad/TieDIE/tiedie.cn.sif", header = FALSE, stringsAsFactors = FALSE)
sif_graph <- graph_from_data_frame(sif_data[,c("V1","V3")], directed = FALSE)
plot(sif_graph, layout = layout.fruchterman.reingold, vertex.size = 5,vertex.frame.color= "white")
```

```{r}
library(igraph)
library(networkD3)

# create a dataset:
data <- data.frame(
  from=c("A", "A", "B", "D", "C", "D", "E", "B", "C", "D", "K", "A", "M"),
  to=c("B", "E", "F", "A", "C", "A", "B", "Z", "A", "C", "A", "B", "K")
)

# Plot
p <- simpleNetwork(data, height="100px", width="100px",        
        Source = 1,                 # column number of source
        Target = 2,                 # column number of target
        linkDistance = 10,          # distance between node. Increase this value to have more space between nodes
        charge = -900,                # numeric value indicating either the strength of the node repulsion (negative value) or attraction (positive value)
        fontSize = 14,               # size of the node names
        fontFamily = "serif",       # font og node names
        linkColour = "#666",        # colour of edges, MUST be a common colour for the whole graph
        nodeColour = "#69b3a2",     # colour of nodes, MUST be a common colour for the whole graph
        opacity = 0.9,              # opacity of nodes. 0=transparent. 1=no transparency
        zoom = T                    # Can you zoom on the figure?
        )
```


