---
title: "Virtual Inference of Protein-activity by Enriched Regulon analysis (Master Regulator Analysis)"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: united
    highlight: textmate
editor_options:
  chunk_output_type: console
---

# Load packages
```{r message=FALSE, warning=FALSE}
library(viper)
library(foreach)
library(doParallel)
```

# Run Viper on CNV
```{r}
# Set up parallel backend
registerDoParallel(5)
# Loop through items in parallel
foreach(name = c("kirc", "hnsc", "lusc", "luad", "paad")) %dopar% {
    dset <- readRDS(paste("output/cnv/dset_", name, ".RDS",
        sep = ""))
    signature <- rowTtest(dset, "description", "tumor", "normal")
    signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * sign(signature$statistic))[,
        1]

    # NULL model by sample permutations

    nullmodel <- ttestNull(dset, "description", "tumor", "normal", per = 1000,
        repos = TRUE, verbose = FALSE)

    # msVIPER

    regulon <- aracne2regulon(paste("output/regulon/regulon", name, ".adj",
            sep = ""), dset, verbose = FALSE)
    regulon

    ## Normalized Enrichment Score (NES)
    mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE, minsize = 10)
    temp <- summary(mrs, length(mrs$regulon))
    temp$Sign <- ifelse(temp$NES > 0, "+", "-")
    if (length(mrs$regulon) >200){
      temp <- temp[(temp$FDR < sort(temp$FDR)[200]), ]
    }
    temp <- temp[, c("Regulon", "NES", "Sign")]
    temp$NES <- abs(temp$NES)
    dir.create(paste("output/cnv/",
        name, "/", sep = ""),showWarnings = F)
    write.table(temp, paste("output/cnv/",
        name, "/cnv.txt", sep = ""), quote = F, sep = "\t", row.names = F,
        col.names = F)
}
```

# Run Viper on Proteomics Data
```{r}
foreach(name = c("kirc", "hnsc", "lusc", "luad", "paad")) %dopar% {
    dset <- readRDS(paste("output/prot/dset_", name, ".RDS",
        sep = ""))
    signature <- rowTtest(dset, "description", "tumor", "normal")
    signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * sign(signature$statistic))[,
        1]

    # NULL model by sample permutations

    nullmodel <- ttestNull(dset, "description", "tumor", "normal", per = 1000,
        repos = TRUE, verbose = FALSE)

    # msVIPER

    regulon <- aracne2regulon(paste("output/regulon/regulon", name, ".adj",
            sep = ""), dset, verbose = FALSE)
    regulon

    ## Normalized Enrichment Score (NES)
    mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE, minsize = 10)
    temp <- summary(mrs, length(mrs$regulon))
    temp$Sign <- ifelse(temp$NES > 0, "+", "-")
    if (length(mrs$regulon) >200){
      temp <- temp[(temp$FDR < sort(temp$FDR)[200]), ]
    }
    temp <- temp[, c("Regulon", "NES", "Sign")]
    temp$NES <- abs(temp$NES)
    dir.create(paste("output/prot/",
        name, "/", sep = ""),showWarnings = F)
    write.table(temp, paste("output/prot/",
        name, "/prot.txt", sep = ""), quote = F, sep = "\t", row.names = F,
        col.names = F)
}
```

# Run Viper on Phosphoproteome Data
```{r}
foreach(name = c("kirc", "hnsc", "lusc", "luad", "paad")) %dopar% {
    dset <- readRDS(paste("output/phos/dset_", name, ".RDS",
        sep = ""))
    signature <- rowTtest(dset, "description", "tumor", "normal")
    signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * sign(signature$statistic))[,
        1]

    # NULL model by sample permutations

    nullmodel <- ttestNull(dset, "description", "tumor", "normal", per = 1000,
        repos = TRUE, verbose = FALSE)

    # msVIPER

    regulon <- aracne2regulon(paste("output/regulon/regulon", name, ".adj",
            sep = ""), dset, verbose = FALSE)
    regulon

    ## Normalized Enrichment Score (NES)
    mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE, minsize = 10)
    temp <- summary(mrs, length(mrs$regulon))
    temp$Sign <- ifelse(temp$NES > 0, "+", "-")
    if (length(mrs$regulon) >200){
      temp <- temp[(temp$FDR < sort(temp$FDR)[200]), ]
    }
    temp <- temp[, c("Regulon", "NES", "Sign")]
    temp$NES <- abs(temp$NES)
    dir.create(paste("output/phos/",
        name, "/", sep = ""),showWarnings = F)
    write.table(temp, paste("output/phos/",
        name, "/phos.txt", sep = ""), quote = F, sep = "\t", row.names = F,
        col.names = F)
}
```

# Run Viper on Methylation Data
```{r}
foreach(name = c("kirc", "hnsc", "lusc", "luad", "paad")) %dopar% {
    dset <- readRDS(paste("output/methy/dset_", name, ".RDS",
        sep = ""))
    signature <- rowTtest(dset, "description", "tumor", "normal")
    signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * sign(signature$statistic))[,
        1]

    # NULL model by sample permutations

    nullmodel <- ttestNull(dset, "description", "tumor", "normal", per = 1000,
        repos = TRUE, verbose = FALSE)

    # msVIPER

    regulon <- aracne2regulon(paste("output/regulon/regulon", name, ".adj",
            sep = ""), dset, verbose = FALSE)
    regulon

    ## Normalized Enrichment Score (NES)
    mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE, minsize = 1)
    temp <- summary(mrs, length(mrs$regulon))
    temp$Sign <- ifelse(temp$NES > 0, "+", "-")
    if (length(mrs$regulon) >200){
      temp <- temp[(temp$FDR < sort(temp$FDR)[200]), ]
    }
    temp <- temp[, c("Regulon", "NES", "Sign")]
    temp$NES <- abs(temp$NES)
    dir.create(paste("output/methy/",
        name, "/", sep = ""),showWarnings = F)
    write.table(temp, paste("output/methy/",
        name, "/methy.txt", sep = ""), quote = F, sep = "\t", row.names = F,
        col.names = F)
}
```

# Run Viper on Gene Expression Data
```{r}
foreach(name = c("kirc", "hnsc", "lusc", "luad", "paad")) %dopar% {
    dset <- readRDS(paste("output/exprs/dset_", name, ".RDS",
        sep = ""))
    signature <- rowTtest(dset, "description", "tumor", "normal")
    signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * sign(signature$statistic))[,
        1]

    # NULL model by sample permutations

    nullmodel <- ttestNull(dset, "description", "tumor", "normal", per = 1000,
        repos = TRUE, verbose = FALSE)

    regulon <- aracne2regulon(paste("output/regulon/regulon", name, ".adj",
            sep = ""), dset, verbose = FALSE)
    regulon

    ## Normalized Enrichment Score (NES)
    mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE, minsize = 10)
    temp <- summary(mrs, length(mrs$regulon))
    temp$Sign <- ifelse(temp$NES > 0, "+", "-")
    if (length(mrs$regulon) >200){
      temp <- temp[(temp$FDR < sort(temp$FDR)[200]), ]
    }
    temp <- temp[, c("Regulon", "NES", "Sign")]
    temp$NES <- abs(temp$NES)
    dir.create(paste("output/exprs/",
        name, "/", sep = ""),showWarnings = F)
    write.table(temp, paste("output/exprs/",
        name, "/exprs.txt", sep = ""), quote = F, sep = "\t", row.names = F,
        col.names = F)
}
```