---
title: "Virtual Inference of Protein-activity by Enriched Regulon analysis (Master Regulator Analysis)"
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: textmate
editor_options:
  chunk_output_type: console
---

# Load packages
```{r message=FALSE, warning=FALSE}
library(viper)
library(foreach)
library(doParallel)
```

# Generating the gene expression signatures
```{r}
# Set up parallel backend
registerDoParallel(10)
# Loop through items in parallel
foreach(name = c("kirc", "hnsc", "lusc", "luad", "paad")) %dopar% {
    dset <- readRDS(paste("output/viper/expr_processed/", name, ".RDS",
        sep = ""))
    signature <- rowTtest(dset, "description", "tumor", "normal")
    signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * sign(signature$statistic))[,
        1]

    # NULL model by sample permutations

    nullmodel <- ttestNull(dset, "description", "tumor", "normal", per = 1000,
        repos = TRUE, verbose = FALSE)

    # msVIPER

    regulon <- readRDS(paste("output/viper/regul_object/", name, ".RDS",
        sep = ""))
    regulon

    ## Normalized Enrichment Score (NES)
    dir.create(paste("output/TieDIE/input/", name, "/", sep = ""), showWarnings = FALSE)
    mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE)
    temp <- summary(mrs, length(mrs$regulon))
    temp$Sign <- ifelse(temp$NES > 0, "+", "-")
    temp <- temp[(temp$p.value < 0.05), ]
    temp <- temp[, c("Regulon", "NES", "Sign")]
    temp$NES <- abs(temp$NES)

    pathways <- read.csv("data/pc-hgnc.sif", sep = "\t", header = F)
    up <- unique(pathways$V1)
    down <- unique(pathways$V3)

    write.table(temp[temp$Regulon %in% up, ], paste("output/TieDIE/input/",
        name, "/upstream.input", sep = ""), quote = F, sep = "\t", row.names = F,
        col.names = F)
    write.table(temp[temp$Regulon %in% down, ], paste("output/TieDIE/input/",
        name, "/downstream.input", sep = ""), quote = F, sep = "\t", row.names = F,
        col.names = F)

    pathways <- pathways[(pathways$V1 %in% temp$Regulon) & (pathways$V3 %in%
        temp$Regulon), ]
    write.table(pathways, paste("output/TieDIE/input/", name, "/pathway.sif",
        sep = ""), quote = F, sep = "\t", row.names = F, col.names = F)
}
```
