---
title: "Virtual Inference of Protein-activity by Enriched Regulon analysis"
output:
  workflowr::wflow_html:
    toc: True
editor_options:
  chunk_output_type: console
---

# Load packages
```{r message=FALSE, warning=FALSE}
library(viper)
library(aracne.networks)
```

# Context-specific networks
```{r}
items <- data(package="aracne.networks")$results[, "Item"]
print(items)
```

```{r}
df <- read.csv("data/aracne.networks.csv")
knitr::kable(df)
```

```{r}
for (item in items) {
    if (!file.exists(paste("data/regulon/", item, ".adj",
            sep = ""))) {
        get(item)
        write.regulon(get(item), file = paste("data/regulon/", item, ".adj",
            sep = ""))
    }
}
```

```{r}
dataset <- read.table(paste("data/regulon/", items[1], ".adj",
            sep = ""), header=TRUE, sep="\t")
for (item in items[-1]){
    temp_dataset <-read.table(paste("data/regulon/", item, ".adj",
            sep = ""), header=TRUE, sep="\t")
    dataset<-rbind(dataset, temp_dataset)
    rm(temp_dataset)
  }
write.table(dataset,"data/regulon/merged.adj",row.names = FALSE,quote = FALSE)
```


```{r}
```


```{r}
data(bcellViper, package="bcellViper")
adjfile <- system.file("aracne", "bcellaracne.adj", package = "bcellViper")
regul <- aracne2regulon(adjfile, dset, verbose = FALSE)
```

```{r}
signature <- rowTtest(dset, "description", c("CB", "CC"), "N")
```

```{r}
signature <- (qnorm(signature$p.value/2, lower.tail = FALSE) * + sign(signature$statistic))[, 1]
```

```{r}
nullmodel <- ttestNull(dset, "description", c("CB", "CC"), "N", per = 1000, repos = TRUE, verbose = FALSE)
```

```{r}
mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE)
```

```{r}
summary(mrs)
```

```{r}
plot(mrs, cex = .7)
```

```{r}
mrs <- ledge(mrs)
summary(mrs)
```

```{r}
signature <- bootstrapTtest(dset, "description", c("CB", "CC"), "N", verbose = FALSE)
mrs <- msviper(signature, regulon, nullmodel, verbose = FALSE)
mrs <- bootstrapmsviper(mrs, "mode")
plot(mrs, cex = .7)
```

```{r}
mrshadow <- shadow(mrs, regulators = 25, verbose = FALSE)
summary(mrshadow)
```

